vim.cmd 'hi clear'
if vim.fn.exists 'syntax_on' == 1 then
  vim.cmd 'syntax reset'
end

vim.o.termguicolors = true
vim.g.colors_name = 'syntaxfm'

local hi = function(name, opts)
  vim.api.nvim_set_hl(0, name, opts)
end

-- UI
hi('Normal',        { fg = '#ffffff', bg = '#111111' })
hi('NormalFloat',   { fg = '#ffffff', bg = '#0c0c0c' })
hi('FloatBorder',   { fg = '#FABF47', bg = '#0c0c0c' })
hi('CursorLine',    { bg = '#1a1a1a' })
hi('CursorLineNr',  { fg = '#FABF47', bold = true })
hi('LineNr',        { fg = '#666666' })
hi('SignColumn',    { bg = '#111111' })
hi('EndOfBuffer',   { fg = '#111111' })
hi('VertSplit',     { fg = '#0c0c0c' })
hi('WinSeparator',  { fg = '#0c0c0c' })
hi('StatusLine',    { fg = '#ffffff', bg = '#0c0c0c' })
hi('StatusLineNC',  { fg = '#666666', bg = '#0c0c0c' })
hi('Pmenu',         { fg = '#ffffff', bg = '#0c0c0c' })
hi('PmenuSel',      { fg = '#111111', bg = '#FABF47', bold = true })
hi('Visual',        { bg = '#2a2a2a' })
hi('Search',        { fg = '#111111', bg = '#FABF47' })
hi('IncSearch',     { fg = '#111111', bg = '#BEFF00' })
hi('MatchParen',    { fg = '#FF807F', bold = true })
hi('ColorColumn',   { bg = '#0c0c0c' })
hi('Folded',        { fg = '#666666', bg = '#0c0c0c' })
hi('Directory',     { fg = '#00FFF5' })
hi('ErrorMsg',      { fg = '#FF807F', bold = true })
hi('WarningMsg',    { fg = '#FABF47', bold = true })

-- Syntax
hi('Comment',       { fg = '#666666' })
hi('Constant',      { fg = '#FABF47' })
hi('String',        { fg = '#CCCCCC' })
hi('Character',     { fg = '#CCCCCC' })
hi('Number',        { fg = '#FABF47' })
hi('Boolean',       { fg = '#BEFF00' })
hi('Float',         { fg = '#FABF47' })
hi('Identifier',    { fg = '#ffffff' })
hi('Function',      { fg = '#FABF47' })
hi('Statement',     { fg = '#FABF47' })
hi('Conditional',   { fg = '#FABF47' })
hi('Repeat',        { fg = '#FABF47' })
hi('Label',         { fg = '#518b8b' })
hi('Operator',      { fg = '#BEFF00' })
hi('Keyword',       { fg = '#FABF47' })
hi('Exception',     { fg = '#FF807F' })
hi('PreProc',       { fg = '#fdf4c1' })
hi('Include',       { fg = '#FABF47' })
hi('Define',        { fg = '#fdf4c1' })
hi('Macro',         { fg = '#fdf4c1' })
hi('PreCondit',     { fg = '#fdf4c1' })
hi('Type',          { fg = '#9a9a9a' })
hi('StorageClass',  { fg = '#FABF47' })
hi('Structure',     { fg = '#9a9a9a' })
hi('Typedef',       { fg = '#9a9a9a' })
hi('Special',       { fg = '#a07d3a' })
hi('SpecialChar',   { fg = '#a89984' })
hi('Tag',           { fg = '#FABF47' })
hi('Delimiter',     { fg = '#d5c5a1' })
hi('SpecialComment',{ fg = '#666666' })
hi('Debug',         { fg = '#FF807F' })
hi('Underlined',    { fg = '#00FFF5', underline = true })
hi('Bold',          { bold = true })
hi('Italic',        { italic = true })
hi('Error',         { fg = '#FF807F' })
hi('Todo',          { fg = '#111111', bg = '#FABF47', bold = true })

-- Diagnostics
hi('DiagnosticError',          { fg = '#FF807F' })
hi('DiagnosticWarn',           { fg = '#FABF47' })
hi('DiagnosticInfo',           { fg = '#00FFF5' })
hi('DiagnosticHint',           { fg = '#BEFF00' })
hi('DiagnosticUnderlineError', { undercurl = true, sp = '#FF807F' })
hi('DiagnosticUnderlineWarn',  { undercurl = true, sp = '#FABF47' })
hi('DiagnosticUnderlineInfo',  { undercurl = true, sp = '#00FFF5' })
hi('DiagnosticUnderlineHint',  { undercurl = true, sp = '#BEFF00' })

-- Treesitter
hi('@variable',              { fg = '#ffffff' })
hi('@variable.builtin',      { fg = '#FF807F' })
hi('@variable.parameter',    { fg = '#ffffff' })
hi('@variable.member',       { fg = '#00FFF5' })
hi('@property',              { fg = '#00FFF5' })
hi('@field',                 { fg = '#00FFF5' })
hi('@function',              { fg = '#FABF47' })
hi('@function.builtin',      { fg = '#FABF47' })
hi('@function.call',         { fg = '#FABF47' })
hi('@function.method',       { fg = '#FABF47' })
hi('@function.method.call',  { fg = '#FABF47' })
hi('@constructor',           { fg = '#518b8b' })
hi('@method',                { fg = '#FABF47' })
hi('@keyword',               { fg = '#FABF47' })
hi('@keyword.function',      { fg = '#FABF47' })
hi('@keyword.return',        { fg = '#FABF47' })
hi('@keyword.operator',      { fg = '#BEFF00' })
hi('@keyword.modifier',      { fg = '#FABF47' })
hi('@conditional',           { fg = '#FABF47' })
hi('@repeat',                { fg = '#FABF47' })
hi('@operator',              { fg = '#BEFF00' })
hi('@string',                { fg = '#CCCCCC' })
hi('@string.escape',         { fg = '#a89984' })
hi('@string.regex',          { fg = '#a07d3a' })
hi('@string.special',        { fg = '#a07d3a' })
hi('@character',             { fg = '#CCCCCC' })
hi('@number',                { fg = '#FABF47' })
hi('@boolean',               { fg = '#BEFF00' })
hi('@type',                  { fg = '#9a9a9a' })
hi('@type.builtin',          { fg = '#9a9a9a' })
hi('@type.definition',       { fg = '#9a9a9a' })
hi('@type.qualifier',        { fg = '#FABF47' })
hi('@constant',              { fg = '#FABF47' })
hi('@constant.builtin',      { fg = '#FABF47' })
hi('@constant.macro',        { fg = '#fdf4c1' })
hi('@module',                { fg = '#ffffff' })
hi('@module.builtin',        { fg = '#FF807F' })
hi('@label',                 { fg = '#518b8b' })
hi('@comment',               { fg = '#666666' })
hi('@punctuation',           { fg = '#ffffff' })
hi('@punctuation.bracket',   { fg = '#FF807F' })
hi('@punctuation.delimiter', { fg = '#d5c5a1' })
hi('@punctuation.special',   { fg = '#d5c5a1' })
hi('@tag',                   { fg = '#FABF47' })
hi('@tag.attribute',         { fg = '#FABF47' })
hi('@markup.heading',        { fg = '#fdf4c1', bold = true })
hi('@markup.italic',         { fg = '#a07d3a', italic = true })
hi('@markup.link',           { fg = '#00FFF5', underline = true })
hi('@markup.raw',            { fg = '#a07d3a' })

-- LSP semantic tokens
hi('@lsp.type.macro',          { fg = '#fdf4c1' })
hi('@lsp.type.enum',           { fg = '#9a9a9a' })
hi('@lsp.type.enumMember',     { fg = '#518b8b' })
hi('@lsp.type.struct',         { fg = '#9a9a9a' })
hi('@lsp.type.type',           { fg = '#9a9a9a' })
hi('@lsp.type.typeParameter',  { fg = '#FF807F' })
hi('@lsp.type.parameter',      { fg = '#ffffff' })
hi('@lsp.type.property',       { fg = '#00FFF5' })
hi('@lsp.type.variable',       { fg = '#ffffff' })
hi('@lsp.type.function',       { fg = '#FABF47' })
hi('@lsp.type.method',         { fg = '#FABF47' })
hi('@lsp.type.namespace',      { fg = '#ffffff' })

-- Rust
hi('Trait', { fg = '#9a9a9a' })
hi('rustAttribute',      { link = 'Macro' })
hi('rustDerive',         { link = 'Trait' })
hi('rustModPath',        { link = 'Identifier' })
hi('rustFuncCall',       { link = 'Function' })
hi('rustFuncName',       { link = 'Function' })
hi('rustCommentLineDoc', { link = 'Comment' })
hi('rustAssert',         { link = 'Macro' })
hi('rustPanic',          { link = 'Macro' })
hi('rustMacro',          { link = 'Macro' })
hi('rustSigil',          { link = 'SpecialChar' })
